### ISSUE TITLE
PCI Coral full_access

### ISSUE THREAD

**Issue by gschrader** [aegjoyce/ha-addons#106]
I'm thinking about moving from Frigate to Scypted for my camera. I see you have the usb option I'm guessing for USB Corals. Is it possibly to add full_access for PCI devices? I think that's the config option that makes the Frigate add-on work.

**Comment by aegjoyce** [comment]
Not keen to add full_access as it will trash the security rating of the add-on. Have added GPIO and UART device inputs with v0.7.24-1, could you see if this fixes the issue?

**Comment by gschrader** [comment]
it didn't find it, I wonder if it needs to be `devices`. On another note when I installed the plugin the readme said it was not used by HomeKit so I might not be completely comprehending everything.

**Comment by aegjoyce** [comment]
Anything that can be exposed in `devices` will be exposed as part of `gpio` `usb` and `uart`. Do you know the hardware address of the Frigate?

**Comment by aegjoyce** [comment]
Screenshots of how you're trying to set it up in Scrypted would be helpful if you can provide them

**Comment by gschrader** [comment]
I can see it in the HAOS terminal under `/dev/apex_0`

Frigate only shows this in the log:
`
[2023-03-23 15:49:36] frigate.edgetpu                INFO    : TPU found
`

I haven't gotten very far with Scrypted yet, but the plugin shows this:

![image](https://user-images.githubusercontent.com/868298/227373110-8b583790-9109-4730-954a-62c4abc721d7.png)

**Comment by gschrader** [comment]
Here's the console:
`
server version: 0.7.24
plugin version: @scrypted/tensorflow-lite 0.1.7
########################
3/23/2023, 3:59:37 PM
########################
python version: python3.9
requirements.txt (up to date)
--extra-index-url https://google-coral.github.io/py-repo/

# plugin
numpy>=1.16.2
# pillow for anything not intel linux
Pillow>=5.4.1; sys_platform != 'linux' or platform_machine != 'x86_64'
pillow-simd; sys_platform == 'linux' and platform_machine == 'x86_64'
pycoral~=2.0
PyGObject>=3.30.4; sys_platform != 'win32'
# libav doesnt work on arm7
av>=10.0.0; sys_platform != 'linux' or platform_machine == 'x86_64' or platform_machine == 'aarch64'
tflite-runtime==2.5.0.post1

# sort_oh
scipy
filterpy

site-packages: /data/scrypted_data/plugins/@scrypted/tensorflow-lite/python3.9-Linux-x86_64/lib/python3.9/site-packages
coral edge tpu library loaded successfully
edge tpus [{'type': 'pci', 'path': '/dev/apex_0'}]
unable to use Coral Edge TPU Failed to load delegate from libedgetpu.so.1

unable to use Coral Edge TPU all tpus failed to load

`

Thought for a second I made a mistake not restarting with your latest version but I presume the version numbers won't match.

**Comment by gschrader** [comment]
looks like it is in the scrypted container:

![image](https://user-images.githubusercontent.com/868298/227385708-88944cd1-733d-4838-96a4-6eeef42db5a7.png)

**Comment by gschrader** [comment]
Looks like frigate specifies some common devices

https://github.com/blakeblackshear/frigate-hass-addons/blob/80879183cb4040e4152bb56d805f2387e24ec884/frigate/config.yaml

**Comment by aegjoyce** [comment]
I think this is a passthrough issue - looks like it needs `--privileged` enabled, I will have another look at this

**Comment by aegjoyce** [comment]
Right, have just made some changes on Scrypted Beta to allow privileged sys_rawio access and /dev/mem access - would you mind testing this out? It's v0.7.85-1

**Comment by gschrader** [comment]
I'm guessing you'd want to copy frigate with this:

```
devices:
  - /dev/dri/renderD128
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/dri/card0
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
```

I specifically would need  `/dev/apex_0`

**Comment by aegjoyce** [comment]
Ok, v0.7.85-2 adds those devices and also adds `video: true` in case that helps

**Comment by aegjoyce** [comment]
This is good news! Would you mind testing v0.7.85-3 and see if it still works? I just removed the `privileged` section from config.yaml. If it still works like this then I'll push it to the main Scrypted addons, happy to have devices specified if it makes the coral work (although I still don't understand why it doesn't work when just `gpio` and all the other settings are enabled - it should!)

**Comment by aegjoyce** [comment]
Closed with latest release.

**Comment by gschrader** [comment]
Yup it still loads with the latest version, thanks for adding it to the main release.
