### ISSUE TITLE
Latest addon based on 0.0.181 wipes config on update

### ISSUE THREAD

**Issue by Ixian** [aegjoyce/ha-addons#11]
I've duplicated this a couple times now - when updating the HA addon (that used Scrypted 0.0.180) to .181 my config is wiped (or it ignores the existing config) and everything needs to be reconfigured. There don't appear to be any breaking changes with Scypted itself so it may be a bug in the addon.

I'm able to roll back to the older version but wanted to let you know in case it's widespread.

**Comment by Ixian** [comment]
Yes. The backup>change>restore doesn't work for me. I don't have a config folder in the backup. I have a data folder that has an empty options.json in it. I'm not sure what's going on. Unfortunately I am running HASSOS still, which means it's a pain in the ass to access the docker data directory for addons directly but I know how to do it and I'll see if I can migrate things that way.

**Comment by Ixian** [comment]
Update: I ran a tmp Alpine image and mounted the HASS /mnt directory to local, then dug around until I found the new and old Scrypted directories. Copied the old data over and everything appears to work with the new version, thanks for the pointers - maybe put that the config directory changed in the release and/or addon notes? If it is it wasn't easy to find. 

Thanks for putting the addon together btw! Appreciate the volunteer work.

**Comment by fisch55** [comment]
same here.... no config folder in backup... for me I does not work!

**Comment by aegjoyce** [comment]
> same here.... no config folder in backup... for me I does not work!

@fisch55 the folder containing your config from pre-0.180 is in a folder called 'scrypted' in your HA folder (the same folder that contains your HA configuration.yaml, groups.yaml etc) NOT the backup you would have downloaded.

First can you confirm that you have found this scrypted folder containing your old config?

Then follow the instructions about editing a backup as per the link I posted above. You might have to create the folder architecture in step 4 if it hasn't already been created.

**Comment by fisch55** [comment]
> First can you confirm that you have found this scrypted folder containing your old config?

yes , the scrypted folder is found.

Should I download backup from the new Version.... I' very confused :-)

**Comment by aegjoyce** [comment]
Ok. Download that scrypted folder to your computer (containing 'plugins' and 'scrypted.db')

Then:

1. Settings - System - Backups - Create Backup - Partial Backup
2. Select Scrypted (only) and Create
3. Download the newly made backup and open it on your computer
4. Copy everything that was in your \config\scrypted folder into [backup name]\scrypted\data\scrypted_data. **so in this case copy 'plugins' and 'scrypted.db' into [backup name]\scrypted\data\scrypted_data**
5. Zip [backup name]\scrypted back up into a **.tar.gz** file 
6. Zip the whole backup folder back up into a **.tar** file
7. On Home Assistant, delete the backup you made, then upload your modified backup file and restore it
