### ISSUE TITLE
404 errors in scrypted after upgrade to `v0.7.97-3`

### ISSUE THREAD

**Issue by bsdlp** [aegjoyce/ha-addons#140]
after taking an upgrade to `v0.7.97-3` for scrypted in homeassistant (i also took homeassistant core upgrade to 2023.5.2 so i'm not sure which update is problematic), i noticed that assets seem to be requested without the `/api/hassio_ingress/xxxxxx` prefix resulting in 404s and a blank page i.e.

```
<link href="/endpoint/@scrypted/core/public/js/chunk-0b65ffb6.f41cd050.js" rel="prefetch">
```

requesting that 404s but if i request `https://homeassistant/api/hassio_ingress/xxxxxx/endpoint/@scrypted/core/public/js/chunk-0b65ffb6.f41cd050.js` that loads just fine

```
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest
```

**Comment by aegjoyce** [comment]
Have you updated scrypted core plugin to latest version?

**Comment by bsdlp** [comment]
hm - i can't seem to replicate this anymore 😅
