### ISSUE TITLE
Not Found v0.7.97-4 

### ISSUE THREAD

**Issue by pandady** [aegjoyce/ha-addons#142]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/46336111/236830914-b82bb3bc-83af-44ac-a0f1-a42d741f0720.png">

23-05-08 20:53:44 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install ghcr.io/aegjoyce/amd64-ha-addon-scrypted:v0.7.97-4: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/aegjoyce/amd64-ha-addon-scrypted:v0.7.97-4/json: Not Found ("No such image: ghcr.io/aegjoyce/amd64-ha-addon-scrypted:v0.7.97-4")

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1

**Comment by aegjoyce** [comment]
I think this must be a connectivity issue - as seen below the image definitely exists and can be downloaded

<img width="788" alt="image" src="https://user-images.githubusercontent.com/47081267/236864386-a0b1c019-8d37-4d9d-9382-a13fd5b5f2c1.png">
