### ISSUE TITLE
Add-on not starting after latest update

### ISSUE THREAD

**Issue by phdonnelly** [aegjoyce/ha-addons#17]
Getting this error in the logs: s6-overlay-suexec: fatal: can only run as pid 1

Think you may need to set init: false in the config.yaml per this post https://community.home-assistant.io/t/hello-world-example-addon-from-developer-docs-stopped-working-s6-overlay-issue/421486

**Comment by DuncanRae** [comment]
Same here. Restore to previous version and all working again.

**Comment by aegjoyce** [comment]
Hopefully now fixed - please try updating back to 0.3.3 or re-installing and let me know - thanks!

**Comment by kurim** [comment]
After downgrade and update again everything is fine.

**Comment by ari-za** [comment]
any suggestions? mine is borked now after a failed update. doesn't seem to successfull restore from any of the backups I have either

**Comment by DuncanRae** [comment]
All good now. Thanks!

**Comment by mdshw5** [comment]
Just a note that some people reported this issue in https://github.com/koush/scrypted/issues/391 as well.
