### ISSUE TITLE
How to add scrypted camera's to dashboard ?

### ISSUE THREAD

**Issue by Vinisz** [aegjoyce/ha-addons#20]
Hi, thanks for this.. one question, how can I add the scrypted camera's to a lovelace dashboard ?

**Comment by aegjoyce** [comment]
You can’t, unless you set up a new rtsp camera component using the rebroadcast url from scrypted. But you might as well just use the url directly from the camera in this scenario. This add-on is purely designed to allow you to instal scrypted on the same hardware as HA OS and does not offer further integration at this time
