### ISSUE TITLE
Switch to full branch

### ISSUE THREAD

**Issue by bordeo** [aegjoyce/ha-addons#22]
Could you switch to full version branch [18-bullseye-full-v0.4.8](https://hub.docker.com/layers/koush/scrypted/18-bullseye-full-v0.4.8/images/sha256-b945cb13ff326132a370d7a85fbb948f1dc43874d3bbb6f5481b4e0ed21477e3?context=explore)? 
Otherwise opencv plugin won’t work because aiofiles and gstreamer is missing

**Comment by aegjoyce** [comment]
Done

**Comment by bordeo** [comment]
Thank you.
I ask due to a problem with opencv. See details [here](https://github.com/koush/scrypted/issues/472).
Could you tag the new release so we can update it in homeassistant?

**Comment by aegjoyce** [comment]
Tagged, should be appearing as an update now

**Comment by bordeo** [comment]
Just updated, all working great. Thank you
