### ISSUE TITLE
manifest for koush/scrypted:0.0.163 not found 

### ISSUE THREAD

**Issue by OXOTH1K** [aegjoyce/ha-addons#3]
Trying to update 156->163 on amd64 take this error:

`Can't install koush/scrypted:0.0.163: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.0.163&fromImage=koush%2Fscrypted&platform=linux%2Famd64: Not Found ("manifest for koush/scrypted:0.0.163 not found: manifest unknown: manifest unknown")
`

**Comment by aegjoyce** [comment]
Fixed - image version numbers now start with 'v' which is why it wouldn't pull.
