### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by tmpneves** [aegjoyce/ha-addons#4]
Maybe a stupid question, but how do I update scrypted without losing my configuration?
Thank you

**Comment by macjuju** [comment]
I have the same question, too. But seems no other better way at this moment as we can not update version requires "new base image" - That's why we could go to 1.7.1 but not 1.7.7. :-(

**Comment by aegjoyce** [comment]
You shouldn't be losing your config when you update - user files should be saved into /config/scrypted. What version are you running and how are you trying to update?
