### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by reesion** [aegjoyce/ha-addons#73]
Hi,

How do I bind a trusted SSL for this? I am trying to make the connection trusted for Alexa integration. 

Thank you.

**Comment by aegjoyce** [comment]
Hopefully this should now work for you with v0.7.81-1, try creating a JSON file per the instructions [here](https://github.com/koush/scrypted/wiki/Custom-SSL-Certificate) and then setting the `SCRYPTED_HTTPS_OPTIONS_FILE` environment variable
