### ISSUE TITLE
Addon storing its data in the config root instead of the addons directory

### ISSUE THREAD

**Issue by phdonnelly** [aegjoyce/ha-addons#9]
Hi,

Thanks for creating this addon; I've recently installed it and run into an issue where my backup size increased by quite a lot, and even when I exclude the add-ons form the backup the size is still large.

I took a quick look and the addon seems to be storing its configuration files in the "/config" directory, which maps to "/usr/share/hassio/homeassistant" and I believe it should be storing this data in the "/data" directory, which maps to "/usr/share/hassio/addons/data/". It looks like all the built-in addons behave this way.

Any chance of updating the config file to use the /data directory? I can try to create a PR for this if that helps.

**Comment by aegjoyce** [comment]
No problem. I set it up this way previously as an easier way to access the scrypted database if people wanted to export their configuration (look at addons like zigbee2mqtt, nodered, esphome which all store some user data in the /config folder). However as the database can get quite big and is stored in the same place as the config I have moved it to /data/scrypted_data as requested

**Comment by aegjoyce** [comment]
Changes will be applied when the scrypted base image next updates
